### ISSUE TITLE
Add support for long-lived tokens

### ISSUE THREAD

**Issue by pstuifzand** [home-assistant/hubot-home-assistant#18]
The api password is deprecated in Home Assistant. It's recommended now to use long-lived access tokens. The homeassistant package supports this already.

**Comment by stephenyeargin** [comment]
Do we know if "deprecated" means already broken or "will break in version ___"?

**Comment by pstuifzand** [comment]
It's discouraged and support will be removed in a future release. Which release is not mentioned.

https://www.home-assistant.io/docs/authentication/providers/#legacy-api-password

**Comment by stephenyeargin** [comment]
See #20 for testing.
