### ISSUE TITLE
cannot install - getting 404 from registry 

### ISSUE THREAD

**Issue by Omermiz** [home-assistant/hubot-home-assistant#4]
Thats what i get when i try to install hubot-home-assistant in the npm logs:
18 http request GET https://registry.npmjs.org/hubot-home-assistant
19 http 404 https://registry.npmjs.org/hubot-home-assistant

if you try to browse the url thats what you get: {}

thats what im getting in the console:

root@raspberrypi:~/hubot-home-assistant# npm install hubot-home-assistant --save
npm ERR! Linux 4.4.38-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "hubot-home-assistant" "--save"
npm ERR! node v4.2.1
npm ERR! npm  v4.0.5

npm ERR! Cannot convert undefined or null to object
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/hubot-home-assistant/npm-debug.log

**Comment by thundergreen** [comment]
Solved by: 

npm install https://github.com/home-assistant/hubot-home-assistant.git --save

But another question: How to confiure the bot? and how to connect an ympp adapter to my server ?

**Comment by stephenyeargin** [comment]
This issue has been resolved by publishing `0.0.1` to NPM. The install instructions above will get you the latest and greatest without waiting on it being published to the directory, but stability may be affected.

https://www.npmjs.com/package/hubot-home-assistant
